cosmetic only

diff --git a/scripts/tests/test-nbh-high b/scripts/tests/test-nbh-high
--- a/scripts/tests/test-nbh-high
+++ b/scripts/tests/test-nbh-high
@@ -45,8 +45,8 @@ function usage() {
 while getopts ":p:" opt; do
     case $opt in
 	p)  period=$OPTARG ;;
-	\?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
-	:)  echo "Option -$OPTARG requires an argument." >&2 ; exit 1 ;;
+	\?) echo "Invalid option: -$OPTARG" >&2; usage ;;
+	:)  echo "Option -$OPTARG requires an argument." >&2 ; usage ;;
   esac
 done
 shift $((OPTIND-1))
