fixes for start-in-dir-as-uid * chown on the landing point * enter the container in /home/jovyan * run jupyter notebook with the option to start in work/ * plus a review of nbh to avoid 'set -e' that would exit   abruptly with no way to ensure proper stdout

diff --git a/scripts/nbh b/scripts/nbh
--- a/scripts/nbh
+++ b/scripts/nbh
@@ -45,6 +45,10 @@ timeout_wait_for_port="10 .1 0"
 # then we wait an extra safety timeout
 timeout_wait_for_http="20 1 3"
 
+# implementation note
+#  don't do set -e, as it may cause the program to exit abruptly
+# and we need to make sure we output exactly one line with 4 tokens
+    
 ########## for listing available subcommands
 SUBCOMMANDS=""
 function @declare-subcommand() {
@@ -588,64 +592,63 @@ function create-docker-container-for-student-in-course() {
     # <=> jupyter's root
     touch $STUDENT_course/.monitor
 
-    #  exit with retcode != 0 if anything goes south
-    set -e
-    
     local jupyter_token=$container
     # check if container container is already defined
-    # beware we are in a set -e section
-    docker inspect --format "{{.Name}}" $container >& /dev/null \
-	&& { \
-	     action="existing"
-	     # this is the case where docker inspect was successful
-    } || { \
-	   action="created"
-	   # this now is when docker inspect fails
-	   -echo-stderr Creating docker container $container
-	   # * map host free port to fixed 8888 in container
-	   # * bind  mounts so that the user's data is on
-	   #   the host filesystem
-	   # * map jovyan uid to the student's
-	   #   from https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook
-	   #   this requires --user root and -e NB_UID=<id>
-	   # * turn off this http header that otherwise would prevent embedding in a FUN iframe
-	   #   Content-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report
-	   #   so set the web server's settings to clear the Content-Security-Policy header
-	   #   it is too tedious on the command line with quoting and all, so
-	   #   let's use the config file instead
-	   ### older notes
-	   # * for turning off token auth, we would need to specify the command to run:
-	   #    --NotebookApp.token=''
-	   ##
-	   # compute student uid
-	   STUDENT_uid=$(id -u $student)
-	   command="docker create --name $container
-	       -p 8888
-	       --user root
-	       -v $STUDENT_course:/home/jovyan/work
-               -v $COURSE_modules:/home/jovyan/modules
-	       -v $COURSE_jupyter/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
-	       -v $COURSE_jupyter/custom.js:/home/jovyan/.jupyter/custom/custom.js
-	       -v $COURSE_jupyter/custom.css:/home/jovyan/.jupyter/custom/custom.css"
-	   for static in $COURSE_statics; do
-	       command="$command -v $NBHROOT/static/$course/$static:/home/jovyan/work/$static"
-	   done
-	   command="$command
-	       -e PYTHONPATH=/home/jovyan/modules
-	       $COURSE_image 
-	       start-in-dir-as-uid.sh /home/jovyan/work $STUDENT_uid
-	       jupyter notebook
-	       --no-browser 
-	       --NotebookApp.token=$jupyter_token 
-"
-	   # --log-level=DEBUG
-	   # show command for manual debugging
-	   -echo-stderr XXXXXXXXXX $command
-	   # we need a clean stdout : redirect stdout to stderr 
-	   >&2 $command
-    }
+    if docker inspect --format "{{.Name}}" $container >& /dev/null ; then
+	action="existing"
+	# this is the case where docker inspect was successful
+    else
+	action="created"
+	# this now is when docker inspect fails
+	-echo-stderr Creating docker container $container
+	# * map host free port to fixed 8888 in container
+	# * bind  mounts so that the user's data is on
+	#   the host filesystem
+	# * map jovyan uid to the student's
+	#   from https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook
+	#   this requires --user root and -e NB_UID=<id>
+	# * turn off this http header that otherwise would prevent embedding in a FUN iframe
+	#   Content-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report
+	#   so set the web server's settings to clear the Content-Security-Policy header
+	#   it is too tedious on the command line with quoting and all, so
+	#   let's use the config file instead
+	### older notes
+	# * for turning off token auth, we would need to specify the command to run:
+	#    --NotebookApp.token=''
+	##
+	# compute student uid
+	STUDENT_uid=$(id -u $student)
+	command="docker create --name $container
+	         -p 8888
+	         --user root
+	         -v $STUDENT_course:/home/jovyan/work
+                 -v $COURSE_modules:/home/jovyan/modules
+	         -v $COURSE_jupyter/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
+	         -v $COURSE_jupyter/custom.js:/home/jovyan/.jupyter/custom/custom.js
+	         -v $COURSE_jupyter/custom.css:/home/jovyan/.jupyter/custom/custom.css"
+	for static in $COURSE_statics; do
+	    command="$command -v $NBHROOT/static/$course/$static:/home/jovyan/work/$static"
+	done
+	# see start-in-dir-as-uid.sh for a note on setting the directories
+	# below
+	command="$command
+	         -e PYTHONPATH=/home/jovyan/modules
+	         $COURSE_image 
+	         start-in-dir-as-uid.sh /home/jovyan $STUDENT_uid
+	         jupyter notebook
+	         --no-browser 
+		 --NotebookApp.notebook_dir=/home/jovyan/work
+	         --NotebookApp.token=$jupyter_token
 
-    -echo-stderr create-docker OK - action=$action
+"
+	[ -n "$debug" ] && command="$command --log-level=DEBUG"
+	# show command for manual debugging
+	-echo-stderr XXXXXXXXXX $command
+	# we need a clean stdout : redirect stdout to stderr 
+	>&2 $command
+    fi
+
+    -echo-stderr create-docker-container-for-student-in-course writes action=$action
     echo $action
     return 0
 }
@@ -734,20 +737,17 @@ function start-docker-container() {
     # <=> jupyter's root
     touch $STUDENT_course/.monitor
 
-    #  exit with retcode != 0 if anything goes south
-    set -e
-    
     local jupyter_token=$container
     # check if container container is already defined
-    # beware we are in a set -e section
-    docker inspect --format "{{.Name}}" $container >& /dev/null \
-	|| { \
-	     action="no-such-container"
-	     echo $action $container 0 none
-    }
+    if ! docker inspect --format "{{.Name}}" $container >& /dev/null; then
+	-echo-stderr "INTERNAL error: cannot start non-existent container $container"
+	action="no-such-container"
+	echo $action $container 0 none
+	return
+    fi
 
-    ### at that point the docker is expected to be created
-    # so: start the container only if it needs to, and in that
+    ### at that point the docker is created
+    # start the container only if it needs to, and in that
     # case wait until it's up and reachable
     running=$(docker inspect -f "{{.State.Running}}" $container)
     # refine action if this container was not just created
